package com.example.ibm.academy.restapi.enumeradores;

public enum TipoTarjetaCredito
{
	TDC_B_SMART,
	TDC_CLASICA,
	TDC_AFINITY_CARD,
	TDC_OFFICE_DEPOT,
	TDC_COSTCO,
	TDC_BEST_BUY_BANAMEX,
	TDC_THE_HOME_DEPOT,
	TDC_ORO,
	TDC_PLATINUM,
	TDC_CITI_AADVANTAGE,
	TDC_BANAMEX_TELETON,
	TDC_APAC,
	TDC_MARTI_CLASICA,
	TDC_AMERICA_DEPORTEISMO,
	TDC_PUMAS_DEPORTEISMO,
	TDC_TOLUCA_DEPORTEISMO,
	TDC_LA_VERDE_DEPORTEISMO,
	TDC_MARTI_PREMIUM_CITIBANAMEX
}
